"""Phase 3B: passport-style output (research prototype, NOT a certified battery passport).

Builds a plain dict from the same `ctx` the Prediction tab uses, and exports it as JSON and as a one-page printable PDF
(matplotlib only - no extra dependency). Fields follow the kind of information Annex XIII of Regulation (EU) 2023/1542 lists for
the battery passport: state of health, expected remaining life (with uncertainty), cycle count, and provenance, plus this project's
own trust status with its stated detection rate. Nothing here is a compliance claim.

Rules kept from the app: no green or "trusted" wording; RUL only under the app's existing condition (nearest known source is NASA
or MIT AND the battery is not flagged); the interval is a 90% conformal interval calibrated on known sources."""
from __future__ import annotations

import io
import json
from datetime import datetime, timezone

DISCLAIMER = ("RESEARCH PROTOTYPE - NOT A CERTIFIED BATTERY PASSPORT. This document is generated by a university research "
              "project (CellSense). It is not issued under, and makes no claim of compliance with, Regulation (EU) 2023/1542. "
              "The numbers are model estimates with the stated uncertainty and limits; they are not measurements and must not be "
              "used for safety-critical, commercial or legal decisions without an independent measured capacity test.")


def _r(x, n=1):
    return None if x is None else round(float(x), n)


def build_passport(ctx: dict, dataset: str, battery_id: str, n_cycles_in_data: int | None, source_note: str | None = None) -> dict:
    import live_inference as li  # local import: keeps this module importable without loading models
    info = ctx.get("domain_info") or {}
    errs = info.get("errors") or {}
    flagged = bool(ctx.get("out_of_domain"))
    rul_hidden = ctx.get("rul_hidden", ctx.get("out_of_domain"))
    rul_shown = (not rul_hidden) and ctx.get("rul_pred") is not None
    trust = ctx.get("trust") or {}
    if flagged:
        status = "Unfamiliar battery - treat predictions with caution"
    else:
        status = "No distribution shift detected (this is not a guarantee)"
    try:
        import encoder_provenance as ep
        routed = "multi-source candidate model" if li._use_candidate(dataset) else (
            "extended-reformulation XGBoost-fusion (validated routing)" if dataset in li.EXTENDED_ROUTED_DATASETS
            else "base XGBoost-fusion model (validated routing)")
        encoder_tag = ep.tag_of(li.MODELS_DIR / ("_candidate_multisource.json" if li._use_candidate(dataset) else "xgb_soh_fusion.json"))
    except Exception:
        routed, encoder_tag = "unavailable", None
    return {
        "document": {"type": "research prototype - NOT a certified battery passport", "regulation_reference": "Regulation (EU) 2023/1542 (Annex XIII fields, for orientation only)",
                     "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "disclaimer": DISCLAIMER},
        "battery": {"battery_id": battery_id, "data_source": dataset,
                    "data_provenance": source_note or ("user-uploaded cycle data" if dataset == "Uploaded" else f"{dataset} public dataset, processed by this project"),
                    "cycles_in_data": n_cycles_in_data, "assessed_cycle": ctx.get("cycle_idx")},
        "state_of_health": {"value_percent": _r(ctx.get("soh_pred")), "interval_90_percent": [_r(ctx.get("soh_conformal_lo")), _r(ctx.get("soh_conformal_hi"))],
                            "interval_note": ("interval calibrated on known sources; its coverage is NOT reliable for this battery" if flagged
                                              else "90% conformal interval calibrated on known sources"),
                            "definition": "discharge capacity relative to the battery's first cycles, in percent"},
        "expected_remaining_life": ({"cycles": _r(ctx.get("rul_pred"), 0), "interval_90_percent": [_r(ctx.get("rul_conformal_lo"), 0), _r(ctx.get("rul_conformal_hi"), 0)],
                                     "unit": "charge/discharge cycles to 80% SOH"} if rul_shown else
                                    {"cycles": None, "shown": False, "reason": ctx.get("rul_hidden_reason") or "not available for this battery",
                                     "rule": "RUL is shown only when the nearest known source is NASA or MIT and the battery is not flagged"}),
        "cycle_count": {"cycles_in_data": n_cycles_in_data, "assessed_cycle": ctx.get("cycle_idx")},
        "trust_status": {"status": status, "flagged_as_unfamiliar": flagged, "score_name": li.OOD_SCORE, "score": _r(trust.get("nll_min"), 2),
                         "flag_threshold": round(li.OOD_NLL_THRESHOLD, 2), "nearest_known_source": trust.get("nearest_source"),
                         "stated_detection_rate": li.OOD_NOVEL_DETECTED, "stated_false_alarm_rate": li.OOD_KNOWN_FALSE_ALARM,
                         "validation": "leave-one-source-out over 16 sources (outputs/toolkit_phase3_trust_threshold_leave_source_out.csv)",
                         "weakest_sources": list(li.OOD_WEAK_SOURCES), "not_detected_note": li.OOD_NOT_DETECTED_LINE,
                         "typical_soh_error_points": {"nearest_source_in_domain": _r(errs.get("in_domain_mae"), 2), "unseen_source_typical": _r(errs.get("unseen_source_typical_mae"), 1)},
                         "guarantee": "none - screening check only"},
        "model_provenance": {"model": routed, "encoder": encoder_tag,
                             "routing_note": "routing was selected on held-out data, so it is a deployment choice, not an unbiased test result"},
    }


def passport_json(p: dict) -> bytes:
    return json.dumps(p, indent=2, ensure_ascii=False).encode("utf-8")


def _wrap(text: str, width: int) -> list[str]:
    import textwrap
    return textwrap.wrap(text, width=width) or [""]


def passport_pdf(p: dict) -> bytes:
    """One printable A4 page rendered with matplotlib (no extra dependency). Neutral colours only."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages

    b, soh, rul, cyc, tr, mp = (p["battery"], p["state_of_health"], p["expected_remaining_life"], p["cycle_count"], p["trust_status"], p["model_provenance"])
    fig = plt.figure(figsize=(8.27, 11.69))
    ax = fig.add_axes([0.07, 0.04, 0.86, 0.92]); ax.axis("off"); ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    y = 1.0

    def line(txt, size=9.5, weight="normal", dy=0.020, x=0.0, color="#222222", style="normal"):
        nonlocal y
        ax.text(x, y, txt, fontsize=size, fontweight=weight, va="top", color=color, fontstyle=style, family="DejaVu Sans")
        y -= dy

    def block(title):
        nonlocal y
        y -= 0.008
        ax.plot([0, 1], [y + 0.004, y + 0.004], color="#888888", lw=0.6)
        y -= 0.006
        line(title, 10.5, "bold", 0.026, color="#1F4E79")

    line("BATTERY PASSPORT - RESEARCH PROTOTYPE", 15, "bold", 0.034, color="#1F4E79")
    line("Not a certified battery passport. Fields are oriented on Regulation (EU) 2023/1542, Annex XIII.", 9, "normal", 0.022, style="italic")
    line(f"Generated (UTC): {p['document']['generated_utc']}", 8.5, dy=0.024, color="#555555")

    block("1. Battery and data-source provenance")
    line(f"Battery ID: {b['battery_id']}"); line(f"Data source: {b['data_source']}")
    for l in _wrap(f"Provenance: {b['data_provenance']}", 105): line(l)
    line(f"Model: {mp['model']}   (encoder: {mp['encoder']})")

    block("2. State of health")
    line(f"State of health: {soh['value_percent']} %", 11, "bold", 0.026)
    line(f"90% interval: {soh['interval_90_percent'][0]} - {soh['interval_90_percent'][1]} %")
    for l in _wrap(soh["interval_note"], 105): line(l, 8.5, color="#555555")
    block("3. Expected remaining life")
    if rul.get("cycles") is not None:
        line(f"Expected remaining life: {int(rul['cycles'])} cycles (to 80% SOH)", 11, "bold", 0.026)
        line(f"90% interval: {int(rul['interval_90_percent'][0])} - {int(rul['interval_90_percent'][1])} cycles")
    else:
        line("Expected remaining life: not shown", 11, "bold", 0.026)
        for l in _wrap(f"Reason: {rul['reason']}", 105): line(l, 8.5, color="#555555")
        for l in _wrap(rul["rule"], 105): line(l, 8.5, color="#555555")
    block("4. Cycle count")
    line(f"Cycles available for this battery in this app: {cyc['cycles_in_data']}    Assessed cycle: {cyc['assessed_cycle']}")

    block("5. Trust status of this assessment")
    line(tr["status"], 11, "bold", 0.026)
    line(f"Nearest known source: {tr['nearest_known_source']}    score {tr['score_name']} = {tr['score']}  (flagged if >= {tr['flag_threshold']})")
    for l in _wrap(f"Stated detection rate: the check flagged {tr['stated_detection_rate']:.1%} of batteries from a source it had never seen and wrongly "
                   f"flagged {tr['stated_false_alarm_rate']:.1%} of batteries from known sources (leave-one-source-out over 16 sources). "
                   f"It is weakest for {', '.join(tr['weakest_sources'])}. {tr['not_detected_note']}", 105): line(l)
    e = tr["typical_soh_error_points"]
    if e["nearest_source_in_domain"] is not None and e["unseen_source_typical"] is not None:
        line(f"Typical SOH error (MAE, points): {e['nearest_source_in_domain']} for the nearest known source vs about {e['unseen_source_typical']} on an unseen source")
    line("Guarantee: none - this is a screening check.", 9, "bold")

    block("6. Disclaimer")
    for l in _wrap(p["document"]["disclaimer"], 100): line(l, 8.5, color="#333333")
    for l in _wrap(mp["routing_note"].capitalize() + ".", 105): line(l, 8, color="#555555")
    buf = io.BytesIO()
    with PdfPages(buf) as pdf:
        pdf.savefig(fig)
    plt.close(fig)
    return buf.getvalue()
